spring:
  application:
    name: ssing-server
  profiles:
    default: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

ssing:
  auth:
    jwt:
      issuer: ssing
      secret: ${SSING_JWT_SECRET:}
      access-token-expiration: PT1H
    refresh-token:
      expiration: P14D
    kakao:
      base-url: https://kapi.kakao.com
      app-id: ${SSING_KAKAO_APP_ID:}
      connect-timeout: PT2S
      read-timeout: PT3S
